#!/bin/bash

if [ $USER != "root" ]
then
    echo "please use root user to run!"
    echo "e.g. sudo ./spi_gpio_wisblock"
    exit
fi

# disable the SPI interface first
sudo raspi-config nonint do_spi 1
echo "SPI interface disbaled temporarily for testing"

# 1. read gpiochip0 8 & 9 input status 
#echo "gpiochip0 chip 8 & 9 initial inputs are:"
#gpioget gpiochip0 8 9
#echo " "

# set gpiochip0 11 and 10 to output low
gpioset gpiochip0 11=0 10=0
# 2. read gpiochip0 8 & 9 input status, should be 0 for both
#echo "8 & 9 input status: should be 0 for both" 
result1=$(gpioget gpiochip0 8 9)
if [ "$result1" = "0 0" ] ; then
    echo "SPI Test 1 result: Succeed!"
else
    echo "SPI Test 1 result: Failed"
    exit
fi
echo " "


# set gpiochip0 11 and 10 to output low
gpioset gpiochip0 11=1 10=1
# 3. read gpiochip0 8 & 9 input status, should be 1 for both
#echo "8 & 9 input status: should be 1 for both" 
result2=$(gpioget gpiochip0 8 9)
if [ "$result2" = "1 1" ] ; then
    echo "SPI Test 2 result: Succeed!"
else
    echo "SPI Test 2 result: Failed"
    exit
fi
echo " "

# re-enable the SPI interface first
sudo raspi-config nonint do_spi 0
echo "SPI test finished, and SPI interface is re-enabled."
echo "Start to test GPIO interface"

# set gpiochip3 0 1 3 4 5 6 and 7 to output high
gpioset gpiochip3 0=1 1=1 3=1 4=1 5=1 6=1 7=1
# 4. read gpiochip3 8 9 11 12 13 14 and 15 input status, should be 1 for all
#echo "gpiochip3 8 9 11 12 13 14 and 15 input status: should be 1 for all" 
result3=$(gpioget gpiochip3 8 9 11 12 13 14 15)
if [ "$result3" = "1 1 1 1 1 1 1" ] ; then
    echo "GPIO Test 1 result: Succeed!"
else
    echo "GPIO Test 1 result: Failed"
    exit
fi
echo " "

# set gpiochip3 0 1 3 4 5 6 and 7 to output low
gpioset gpiochip3 0=0 1=0 3=0 4=0 5=0 6=0 7=0
# 5. read gpiochip3 8 9 11 12 13 14 and 15 input status, should be 0 for all
#echo "gpiochip3 8 9 11 12 13 14 and 15 input status: should be 0 for all" 
result4=$(gpioget gpiochip3 8 9 11 12 13 14 15)
if [ "$result4" = "0 0 0 0 0 0 0" ] ; then
    echo "GPIO Test 2 result: Succeed!"
else
    echo "GPIO Test 2 result: Failed"
    exit
fi
echo " "

# set gpiochip3 0 1 3 4 to output high, 5 6 and 7 to output low 
gpioset gpiochip3 0=1 1=1 3=1 4=1 5=0 6=0 7=0
# 5. read gpiochip3 8 9 11 12 13 14 and 15 input status, should be 1 1 1 1 0 0 0 
#echo "gpiochip3 8 9 11 12 13 14 and 15 input status: should be 1 1 1 1 0 0 0" 
result5=$(gpioget gpiochip3 8 9 11 12 13 14 15)
if [ "$result5" = "1 1 1 1 0 0 0" ] ; then
    echo "GPIO Test 3 result: Succeed!"
else
    echo "GPIO Test 3 result: Failed"
    exit
fi
echo " "






